title: ScotopicLabs
description: ScotopicLabs is a startup delivering services in the area of light pollution studies and embedded astronomy systems.
logo: /assets/img/logo.jpg
show_downloads: false
theme: jekyll-theme-minimal
